### PR TITLE
Breakout pieces from interactive.

### PR DESCRIPTION
**Pull request by ehebert**
MAINT: Move expr and compute pieces out interactive.

    Move the `_Data` class and rename it to `Data`.
    (A soon to follow patch will add a `Literal` class from which `Data` will
    inherit, and change dispatches to use `Literal`.)

    Also, move compute and coerce functions into compute.core.

    This is part of the effort of supporting a literal type which is importable from
    expr instead of interactive.

### CODE REVIEW

**Comment by ehebert** [comment]
This includes https://github.com/blaze/blaze/pull/1636

**Comment by ehebert** [comment]
@llllllllll I fixed up the __future__ imports (for Python 2.7), and rebased against HEAD master (which contained #1637). This is green now, and ready for review.

**Comment by llllllllll** [comment]
Thanks for this, I just have one request: can you add something like:

```python
def data(*args, **kwargs):
    warnings.warn(DeprecationWarning('blaze.interactive.data has been moved to blaze.data'))
    return blaze.literal.data(*args, **kwargs)
```

so that any external code that did `from blaze.interactive import data` continues to work.

**Comment by ehebert** [comment]
@llllllllll I added in the deprecation warning:

```
In [1]: import warnings

In [2]: warnings.filterwarnings('always')

In [3]: from blaze.interactive import data

In [4]: data(frozenset([1, 2, 3]))
/home/ehebert/src/quantopian/blaze/blaze/interactive.py:34: DeprecationWarning: blaze.interactive.data has been moved to blaze.data
  warnings.warn(DeprecationWarning('blaze.interactive.data has been moved to blaze.data'))
Out[4]: <'frozenset' data; _name='None', dshape='3 * int64'>
```

**Comment by ehebert** [comment]
I can not yet reproduce the test errors in `blaze/compute/tests/test_dask.py` in my local Python 2 install.
(https://travis-ci.org/blaze/blaze/jobs/229914873)

**Pull request merged**
