### PR TITLE
Fix reduction types that could come from decimal children

### PR DESCRIPTION
**Pull request by cpcloud**

### CODE REVIEW

**Comment by cpcloud** [comment]
@llllllllll any comments here?

**Comment by llllllllll** [comment]
should all reductions be optional aware? Also, where is the code that updates sum?

**Comment by cpcloud** [comment]
sorry, yeah `sum` is update via the recent datashape maxtype fix

**Comment by cpcloud** [comment]
yeah all reductions should be option aware

**Comment by cpcloud** [comment]
actually, something like count shouldn't be

**Comment by cpcloud** [comment]
so not all

**Comment by llllllllll** [comment]
Ah, good point. Looks good.

**Comment by cpcloud** [comment]
merging on pass

**Pull request merged**
