### PR TITLE
Foreign key support

### PR DESCRIPTION
**Pull request by cpcloud**
related: ContinuumIO/odo#274, ContinuumIO/datashape#164

Both of the above PRs need to be merged before merging this one

### CODE REVIEW

**Comment by llllllllll** [comment]
This looks pretty straight forward, I will try to run this locally tomorrow.

**Comment by jreback** [comment]
@cploud this can be merged into master now?

**Comment by cpcloud** [comment]
@llllllllll is there anyway you can run some of the quantopian test suite against this PR before we merge it?

**Comment by llllllllll** [comment]
I will run our tests now, thanks

**Comment by llllllllll** [comment]
All tests for our main blaze based project are passing, thanks!

**Comment by cpcloud** [comment]
@llllllllll awesome, thanks for testing!

**Comment by cpcloud** [comment]
ok merging on next pass

**Pull request merged**
