### PR TITLE
Add test for join type promotion in postgresql

### PR DESCRIPTION
**Pull request by cpcloud**

### CODE REVIEW

**Comment by llllllllll** [comment]
Did you run into the issue where using url as a fixture caused both to get the same url?

**Comment by cpcloud** [comment]
yes i think i'm misunderstanding how the fixture is being executed

**Comment by llllllllll** [comment]
I looked into this, I think there is no scope that means "each time this is called" so each fixture is cached per test

**Comment by cpcloud** [comment]
ok is there a pytest doc for this

**Comment by llllllllll** [comment]
This doesn't really explicitly state it, but this is what I was looking at: https://pytest.org/latest/fixture.html#fixtures-as-function-arguments

**Comment by cpcloud** [comment]
ok thanks. i'm going to change the url stuff around a bit here before merging

**Pull request merged**
