### PR TITLE
fix doc errors

### PR DESCRIPTION
**Pull request by electronwill**
fix doc errors

### CODE REVIEW

**Comment by llllllllll** [comment]
Why did you change all of the underline levels?

**Comment by electronwill** [comment]
We're copying the Blaze docs into the overall Anaconda docs at https://docs.continuum.io/docs_oss/blaze/ so that customers with an offline installation of Anaconda Repository or Anaconda Enterprise Notebooks will have them. Until now, the Sphinx documentation build system has been producing lots of errors, partly because the underlines in these release notes are inconsistent with each other and with the Sphinx preferred underlines at https://docs.python.org/devguide/documenting.html#sections . This PR should fix all of these errors.

**Comment by electronwill** [comment]
@postelrich , would you please merge this one or let me know what else I should do to make this ready to merge?

**Comment by necaris** [comment]
@electronwill it looks like this is failing because of failures on master -- #1656 needs to be merged first before that will be good.

@postelrich note that these are _just_ docs changes so I'd have no objection to merging them despite CI failure -- I'll do this tomorrow unless you'd rather I don't.

**Comment by electronwill** [comment]
Oh, OK, that makes sense. Thanks!

**Pull request merged**
