### PR TITLE
Update introduction

### PR DESCRIPTION
**Pull request by mrocklin**
1.  Link to datashape
2.  Describe multiple backends functionality in leading paragraph
3.  Distinguish between project and ecosystem

Continues the discussion from #1197 

Feedback/suggestions/edits welcome.

### CODE REVIEW

**Comment by cpcloud** [comment]
@mrocklin Can you resolve the merge conflicts here and I'll merge this?

**Comment by mrocklin** [comment]
Sure.  It looks like Travis snuck in some edits.  I'll do what I can to preserve the intent of both.

**Comment by mrocklin** [comment]
Done.  The whole front-page could use further review though.

**Comment by cpcloud** [comment]
Thanks @mrocklin

**Pull request merged**
