### PR TITLE
Add empty __slots__ to Expr and Node classes.

### PR DESCRIPTION
**Pull request by kwmsmith**
See issue #1268.

Consistently uses `__slots__` in class hierarchies, even when empty.

### CODE REVIEW

**Comment by cpcloud** [comment]
Hm it'd be great to have a test. Maybe something as simple as

```
assert Expr.__slots__ == ()
assert Node.__slots__ == ()
```

**Comment by cpcloud** [comment]
When you're ready to merge please also add a tiny release note blurb to `docs/source/whatsnew/0.5.0.txt`

**Comment by kwmsmith** [comment]
I agree a test would be good, but it feels strange to test an internal detail like "does this class have an empty `__slots__`."  It feels like testing the API for a private method.  I don't know of any better way to test for this, though, so I'll add the asserts you mention.

**Comment by cpcloud** [comment]
Yes that test is definitely a bit awkward. If there's a way to test it using the user facing API, by all means

**Comment by kwmsmith** [comment]
> When you're ready to merge please also add a tiny release note blurb to docs/source/whatsnew/0.5.0.txt

Should that be `0.8.4.txt`?  The latest tag I see is `0.8.3`.

**Comment by cpcloud** [comment]
Sorry I meant 0.9.0. I've moved the version to a new minor version since we're dropping support for things.

**Comment by cpcloud** [comment]
@kwmsmith merge master back into your branch it should be passing now

**Pull request merged**
