### PR TITLE
Issue #1546: Fix equality failure for simple types.

### LINKED ISSUE #1546: Data constructor requires 'name' to be set
If the optional ```name``` argument in the ```data``` function isn't set, some operations behave unexpectedly:

```python
>>> from blaze import data, compute
>>> 
>>> xd = data(157)
>>> yd = data(101)
>>> compute(xd == yd)
True
```

This could be prevented by automatically generating unique symbols:

```python

>>> xd = data(157, name="__v0001")
>>> yd = data(101, name="__v0002")
>>> compute(xd == yd)
False
```

### PR DESCRIPTION
**Pull request by skrah**
This fixes #1546 until a way is found to support name=None for equality.

### CODE REVIEW

**Comment by kwmsmith** [comment]
So the result of this change is that all `_Data` objects will have a non-None `name` attribute, which will disambiguate them when equality testing?  Makes sense to me.  Should we go a step further and validate the `name` type if passed in -- something like:

```
if not isinstance(name, str):
   raise ValueError(...)
```

Even more thorough would be to disallow `name` to be the name of an existing `_Data` object, but that's probably outside the scope of this PR.

@llllllllll do you know why the original logic had the `isrecord()` special case?

**Comment by skrah** [comment]
Yes, checking for uniqueness would be good:

```
>>> x = data(1, name='_4')
>>> y = data(2, name='_4')
>>> 
>>> x == y
True
```

But I also think it's better for a separate issue.

**Comment by llllllllll** [comment]
Why does the name need to be unique, if we just make `data` hash like the other expr types then `data(1, name='_4') is data(1, name='_4')`

**Comment by llllllllll** [comment]
Also the record stuff is old, that is just so that tables automagically get named things like `_%d`. We could just always do that.

**Comment by skrah** [comment]
The underlying problem is here:

https://github.com/blaze/blaze/blob/master/blaze/compute/core.py#L330s

toolz.merge() eliminates keys with the same name.


I'm still unsure what namespace guarantees blaze makes, but as a new user I'd probably expect this:

All names of the form "_123" are unique and reserved for internal use (we could actually check for that).

If a non-reserved name is assigned and re-used: Is there some sort of name-binding model that says that old names stay bound?

All names seem global to me, in which case I'd either expect that the new object with the same name overrides the old one entirely or that an error is raised.

**Comment by postelrich** [comment]
Closing to cleanup old PRs. Feel free to submit a new PR.

**Pull request closed without merging**
