### PR TITLE
Weakmemoize and cleanup

### PR DESCRIPTION
**Pull request by llllllllll**
Fixes the leak that we talked about and makes all of the expressions cache their dshape and schema methods.

Also some general cleanup that I saw while making the mostly mechanical changes.

### CODE REVIEW

**Comment by llllllllll** [comment]
tests are failing because of: https://github.com/blaze/blaze/issues/1320

**Comment by cpcloud** [comment]
@llllllllll can you restart this build

**Comment by llllllllll** [comment]
sure, let me rebase away the conflicts too

**Comment by cpcloud** [comment]
@llllllllll don't rebase yet! i'm reviewing

**Comment by llllllllll** [comment]
oh, sorry. I will hold off on that.

**Comment by cpcloud** [comment]
@llllllllll I'm done reviewing if you want to rebase

**Comment by cpcloud** [comment]
you need to either rebase on top of master or merge it in and resolve the conflicts as well as get the change that fixes the failing test

**Comment by llllllllll** [comment]
Added a section in the docs on adding new expressions where I cover the `_dshape` method.

**Comment by cpcloud** [comment]
@llllllllll thanks!

**Comment by llllllllll** [comment]
no, thank you

**Pull request merged**
